name: Run tests on every push and PR

on:
  # run on every push
  push:
  # run on every PR
  pull_request_target:
  # allow it to be run manually
  workflow_dispatch:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute Gradle checks
        # gradle build runs all tests and checks;
        # excluding spotlessApply makes the formatter warn about formatting errors
        # instead of automatically fixing them, which is bad for CI
        run: ./gradlew build -x spotlessApply
