name: Deploy Javadoc

on:
    push:
    workflow_dispatch:

jobs:
    generate:
        runs-on: ubuntu-latest
        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
            pages: write      # to deploy to Pages
            id-token: write   # to verify the deployment originates from an appropriate source

        steps:
            - uses: actions/checkout@v4
              
            - uses: actions/setup-java@v4
              with:
                distribution: temurin
                java-version: 21


            - uses: burrunan/gradle-cache-action@v3
              name: build javadocs
              with:
                  # Specifies arguments for Gradle execution
                  # If arguments is missing or empty, then Gradle is not executed
                  arguments: javadoc
                  # arguments can be multi-line for better readability
                  # arguments: |
                  #  --no-paralell
                  #  build
                  #  -x test
                  # Gradle version to use for execution:
                  #   wrapper (default), current, rc, nightly, release-nightly, or
                  #   versions like 6.6 (see https://services.gradle.org/versions/all)
                  gradle-version: wrapper

            - name: Upload static files as artifact
              id: deployment
              uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
              with:
                path: build/docs/javadoc # Path to the directory containing the static files to be uploaded

    # Deployment job
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: generate
        steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
